[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
cache_path = 'forge-cache'
solc = '0.8.13'
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config