name: Format Checks

on:
  push:

jobs:
  run-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: add node toolchain
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install node dependencies
        run: yarn

      - name: run formatting checks
        run: yarn format:check
