name: Lint Checks

on:
  push:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hours, perpetual fuzz testing

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: add node toolchain
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install node dependencies
        run: yarn

      - name: run linting checks
        run: yarn lint
