name: Mythril Checks
on:
  push:

jobs:
  run-mythril:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: StakingContract
        uses: ./actions/mythril
        id: staking-contract
        with:
          contract: './src/contracts/StakingContract.sol'
