
# action.yml
name: 'Mythril'
description: 'Run Mythril'
inputs:
  contract:
    description: 'Contract to test'
    required: true
runs:
  using: 'docker'
  image: 'mythril/myth:0.23.22'
  args:
    - '-v'
    - '4'
    - 'analyze'
    - ${{ inputs.contract }}
    - '--max-depth'
    - '15'